config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users
  resources :recipes do
    resources :preparations, only: [:new, :create, :destroy]
    resources :steps, only: [:new, :create, :destroy]
  end
  resources :ingredients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
end

app/models/preparation.rb
class Preparation < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  DIFFICULTY = ["très facile", "facile", "moyen", "avancé"]
  DIET = ["vegan", "vegetarienne", "carnivore"]

  belongs_to :user
  has_many :preparations
  has_many :steps
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/preparations_controller.rb
class PreparationsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @preparation = Preparation.new
    authorize @recipe
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = Ingredient.find(params[:ingredient_id])
    @preparation = Preparation.new(prepapration_params)
    @preparation.recipe = @recipe
    @preparation.ingredient = @ingredient
    @preparation.save!
    authorize @preparation
  end

  def destroy
    @preparation = Preparation.find(params[:preparation_id])
    @preparation.delete
    authorize @preparation
  end

  private

  def preparation_params
    params.require(:preparation).permit(:quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def new
    @recipe = Recipe.new
    authorize @recipe
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    @recipe.save!
    authorize @recipe
    redirect_to new_recipe_preparation_path(@recipe)
  end

  def show
    @recipe = Recipe.find(params[:recipe_id])
    authorize @recipe
  end

  def index
    @recipes = Recipe.all
    authorize @recipes
  end

  def update
    @recipe = Recipe.find(params[:recipe_id])
    authorize @recipe
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    authorize @recipe
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @recipe.preparations.destroy_all
    @recipe.steps.destroy_all
    @recipe.delete
    authorize @recipe
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :number_of_people, :diet)
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @step = Step.new
    authorize @recipe
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @step = Step.new(step_params)
    @step.recipe = @recipe
    @step.save!
    authorize @recipe
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @step = Step.new(step_params)
    @step.delete
    authorize @recipe
  end

  private

  def step_params
    params.require(:step).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/preparations_helper.rb
module PreparationsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yummissime</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/tom-select@2.2.2/dist/css/tom-select.css" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>yummissime.</h1>

app/views/preparations/new.html.erb
<h1 class="page-title">Nouvelle recette.</h1>
<%= simple_form_for (@preparation), url: recipe_preparations_path(recipe_id: @recipe.id) do |f| %>
  <%= f.input :quantity, label: "Quantité :"%>
  <%= f.input :ingredient, collection: Ingredient.all, input_html: {data: {controller: "tom-select"}} %>
  <%= f.button :submit, "Ajouter l'ingrédient"%>
<% end %>
<%= link_to "Plus d'ingrédients à ajouter", recipe_steps_path(recipe_id: @recipe.id), class: "primary-btn"  %>
<% if @recipe.preparations.any? %>
  <h3>Ingrédients :</h3>
  <% @recipe.preparations.each do |preparation| %>
  <% end %>
<% end %>

app/views/recipes/new.html.erb
<h1 class="page-title">Nouvelle recette.</h1>
<%= simple_form_for @recipe do |f| %>
  <%= f.input :name, label: "Nom de la recette :"%>
  <div class="form-inline-container">
      <%= f.input :diet, collection: Recipe::DIET, label: "Régime alimentaire :" %>
  <%= f.input :difficulty, collection: Recipe::DIFFICULTY, label: "Difficulté :" %>
  </div>
  <%= f.input :preparation_time, label: "Temps de préparation :" %>
  <%= f.input :cooking_time, label: "Temps de cuisson :" %>
  <%= f.input :number_of_people, label: "Nombre de personne :" %>
  <%= f.button :submit, "Étape suivante"%>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>